version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m

    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Gradle build
          command: ./gradlew assembleRelease
          environment:
            TERM: dumb
